# this file is a helper to run the web application locally
# starts a postgres instance, localstack for S3, and the Next.js web app
version: "3.6"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/verceldb
      - NEXT_PUBLIC_S3_ENDPOINT=http://localhost:4566
    depends_on:
      - postgres
      - localstack
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  postgres:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verceldb
    ports:
      - "5480:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5481:80"
    depends_on:
      - postgres
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./aws:/etc/localstack/init/ready.d
      - ./aws:/app/web/aws
